export class Car{
    ID?:number=0;
    Name:string='';
    PlaceNumber:number=0;
    NumbreDoors:number=0;
    Color:string='';
    PricePerDay:string='';
    Photo:string='';
    Marque:string='';
    Categorie:string='';
    Description:string='';
    Fuel:string='';
    KM:string='';
    BagsNumber:string='';
    Bluetooth:boolean=false;
    AirConditioner:boolean=false;
    AirBag:boolean=false;
    GPS:boolean=false;
}